/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.ccs.cs5200.mbps.ldb.view.member;

import java.awt.CardLayout;
import neu.ccs.cs5200.mbps.ldb.model.Member;
import neu.ccs.cs5200.mbps.ldb.nav.Navigator;
import neu.ccs.cs5200.mbps.ldb.view.util.Registry;
import neu.ccs.cs5200.mbps.ldb.view.util.ViewConstants;

/**
 * The home screen for a logged-in member. From here a member can perform 
 * several tasks listed in their navigation panel.
 * 
 * @author Matt
 */
public class MemberHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form MemberHomeScreen
     */
    public MemberHomeScreen() {
        initComponents();
        
        // register the member navigation options so they can be retrieved later
        (Navigator.getInstance()).register(ViewConstants.Member.NAVIGATOR, viewPanel);
        
        // display the book search by default
        CardLayout cl = (CardLayout) viewPanel.getLayout();
        cl.show(viewPanel, ViewConstants.Member.BOOK_SEARCH);
        
        // set the page title
        Member m = (Member) (Registry.getInstance()).get(ViewConstants.SESSION_MEMBER);
        this.setTitle(ViewConstants.TITLE + " Member: " + m.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberNavigationPanel = new neu.ccs.cs5200.mbps.ldb.view.member.MemberNavigationPanel();
        viewPanel = new javax.swing.JPanel();
        viewWishList = new neu.ccs.cs5200.mbps.ldb.view.member.ViewWishList();
        memberBookSearch = new neu.ccs.cs5200.mbps.ldb.view.member.MemberBookSearch();
        viewDues = new neu.ccs.cs5200.mbps.ldb.view.member.ViewDues();
        viewProfile = new neu.ccs.cs5200.mbps.ldb.view.member.ViewProfile();
        viewCheckedOutBooks = new neu.ccs.cs5200.mbps.ldb.view.member.ViewCheckedOutBooks();
        deleteMembership = new neu.ccs.cs5200.mbps.ldb.view.member.DeleteMembership();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MBPS Library Member");

        viewPanel.setLayout(new java.awt.CardLayout());
        viewPanel.add(viewWishList, "memberViewWishList");
        viewPanel.add(memberBookSearch, "memberBookSearch");
        viewPanel.add(viewDues, "memberViewDues");

        viewProfile.setPreferredSize(new java.awt.Dimension(440, 356));
        viewPanel.add(viewProfile, "memberViewProfile");
        viewPanel.add(viewCheckedOutBooks, "memberViewCheckedOutBooks");
        viewPanel.add(deleteMembership, "deleteMembership");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(memberNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(memberNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberHomeScreen().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private neu.ccs.cs5200.mbps.ldb.view.member.DeleteMembership deleteMembership;
    private neu.ccs.cs5200.mbps.ldb.view.member.MemberBookSearch memberBookSearch;
    private neu.ccs.cs5200.mbps.ldb.view.member.MemberNavigationPanel memberNavigationPanel;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewCheckedOutBooks viewCheckedOutBooks;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewDues viewDues;
    private javax.swing.JPanel viewPanel;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewProfile viewProfile;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewWishList viewWishList;
    // End of variables declaration//GEN-END:variables
}
