/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.ccs.cs5200.mbps.ldb.view.member;

import neu.ccs.cs5200.mbps.ldb.jdbc.LDBConnector;
import neu.ccs.cs5200.mbps.ldb.model.Member;
import neu.ccs.cs5200.mbps.ldb.nav.Navigator;
import neu.ccs.cs5200.mbps.ldb.view.util.Registry;
import neu.ccs.cs5200.mbps.ldb.view.util.ViewConstants;

/**
 * View the current member's profile information.
 * 
 * @author Matt
 */
public class ViewProfile extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfile
     */
    public ViewProfile() {
        initComponents();
        registerViewProfilePanel();
    }
    
    
    /**
     * Register with the navigator so that the profile can be forced to reload
     * its values from the database.
     */
    private void registerViewProfilePanel() {
        (Navigator.getInstance()).register(ViewConstants.Member.VIEW_PROFILE, this);
    }
    
    
    /**
     * Query the database for the current Member's profile details
     */
    public void loadProfile() {
        
        // given the current member login info, get the rest of their profile information 
       Member sessionMember = (Member) (Registry.getInstance()).get(ViewConstants.SESSION_MEMBER);
       sessionMember = (LDBConnector.getInstance()).viewMyProfile(sessionMember.getMemberID());
       
       // set the profile information
       this.memberIdTextField.setText("" + sessionMember.getMemberID());
       this.nameTextField.setText(sessionMember.getName());
       this.emailTextField.setText(sessionMember.getEmail());
       this.addressTextField.setText(sessionMember.getAddress());
       this.phoneNumberTextField.setText(sessionMember.getPhoneNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JLabel();
        emailTextField = new javax.swing.JLabel();
        memberIdTextField = new javax.swing.JLabel();
        addressTextField = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        titleLabel.setText("My Profile");

        nameTextField.setText("[name]");

        emailTextField.setText("[email]");

        memberIdTextField.setText("[member ID]");

        addressTextField.setText("[address]");

        phoneNumberTextField.setText("[phone number]");

        jLabel7.setText("Member ID:");

        jLabel8.setText("Name:");

        jLabel9.setText("EMail:");

        jLabel10.setText("Address:");

        jLabel11.setText("Phone Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField)
                    .addComponent(phoneNumberTextField)
                    .addComponent(addressTextField)
                    .addComponent(memberIdTextField)
                    .addComponent(emailTextField))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(titleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberIdTextField)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberTextField)
                    .addComponent(jLabel11))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressTextField;
    private javax.swing.JLabel emailTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel memberIdTextField;
    private javax.swing.JLabel nameTextField;
    private javax.swing.JLabel phoneNumberTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
