/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.ccs.cs5200.mbps.ldb.view.admin;

import java.awt.CardLayout;
import neu.ccs.cs5200.mbps.ldb.model.Administrator;
import neu.ccs.cs5200.mbps.ldb.nav.Navigator;
import neu.ccs.cs5200.mbps.ldb.view.util.Registry;
import neu.ccs.cs5200.mbps.ldb.view.util.ViewConstants;

/**
 * The home screen for Administrators. Admins can perform all of the basic 
 * functions that a Member can, plus respond to membership requests.
 * 
 * @author Matt
 */
public class AdminHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomeScreen
     */
    public AdminHomeScreen() {
        initComponents();
        
        
        // register the admin navigation options so they can be retrieved later
        (Navigator.getInstance()).register(ViewConstants.Admin.NAVIGATOR, viewPanel);
        
        // display the book search by default
        CardLayout cl = (CardLayout) viewPanel.getLayout();
        cl.show(viewPanel, ViewConstants.Member.BOOK_SEARCH);
        
        // set the page title
        Administrator a = (Administrator) (Registry.getInstance()).get(ViewConstants.SESSION_MEMBER);
        this.setTitle(ViewConstants.TITLE + " Administrator: " + a.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminNavigationPanel = new neu.ccs.cs5200.mbps.ldb.view.admin.AdminNavigationPanel();
        viewPanel = new javax.swing.JPanel();
        viewProfile1 = new neu.ccs.cs5200.mbps.ldb.view.member.ViewProfile();
        viewWishList1 = new neu.ccs.cs5200.mbps.ldb.view.member.ViewWishList();
        viewDues1 = new neu.ccs.cs5200.mbps.ldb.view.member.ViewDues();
        viewCheckedOutBooks1 = new neu.ccs.cs5200.mbps.ldb.view.member.ViewCheckedOutBooks();
        memberBookSearch1 = new neu.ccs.cs5200.mbps.ldb.view.member.MemberBookSearch();
        deleteMembership1 = new neu.ccs.cs5200.mbps.ldb.view.member.DeleteMembership();
        respondRequests1 = new neu.ccs.cs5200.mbps.ldb.view.admin.RespondRequests();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MBPS Library Administrator");

        viewPanel.setLayout(new java.awt.CardLayout());
        viewPanel.add(viewProfile1, "memberViewProfile");
        viewPanel.add(viewWishList1, "memberViewWishList");
        viewPanel.add(viewDues1, "memberViewDues");
        viewPanel.add(viewCheckedOutBooks1, "memberViewCheckedOutBooks");
        viewPanel.add(memberBookSearch1, "memberBookSearch");
        viewPanel.add(deleteMembership1, "deleteMembership");
        viewPanel.add(respondRequests1, "adminRespondRequests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
            .addComponent(viewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomeScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private neu.ccs.cs5200.mbps.ldb.view.admin.AdminNavigationPanel adminNavigationPanel;
    private neu.ccs.cs5200.mbps.ldb.view.member.DeleteMembership deleteMembership1;
    private neu.ccs.cs5200.mbps.ldb.view.member.MemberBookSearch memberBookSearch1;
    private neu.ccs.cs5200.mbps.ldb.view.admin.RespondRequests respondRequests1;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewCheckedOutBooks viewCheckedOutBooks1;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewDues viewDues1;
    private javax.swing.JPanel viewPanel;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewProfile viewProfile1;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewWishList viewWishList1;
    // End of variables declaration//GEN-END:variables
}
