/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package neu.ccs.cs5200.mbps.ldb.view.librarian;

import java.awt.CardLayout;
import javax.swing.JFrame;
import neu.ccs.cs5200.mbps.ldb.model.Librarian;
import neu.ccs.cs5200.mbps.ldb.nav.Navigator;
import neu.ccs.cs5200.mbps.ldb.view.util.Registry;
import neu.ccs.cs5200.mbps.ldb.view.util.ViewConstants;

/**
 * The home screen for Librarians. Librarians can perform all of the basic 
 * functions that a Member can, plus manage the library inventory and check out
 * books to members.
 * 
 * @author prathmeshjakkanwar
 */
public class LibrarianHomeScreen extends JFrame {

    /**
     * Creates new form EditBook
     */
    public LibrarianHomeScreen() {
        initComponents();
        
        // register the librarian navigation options so they can be retrieved later
        (Navigator.getInstance()).register(ViewConstants.Librarian.NAVIGATOR, viewPanel);
        
        // display the book search by default
        CardLayout cl = (CardLayout) viewPanel.getLayout();
        cl.show(viewPanel, ViewConstants.Member.BOOK_SEARCH);
        
        // set the page title
        Librarian l = (Librarian) (Registry.getInstance()).get(ViewConstants.SESSION_MEMBER);
        this.setTitle(ViewConstants.TITLE + " Librarian: " + l.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JPanel();
        viewProfile1 = new neu.ccs.cs5200.mbps.ldb.view.member.ViewProfile();
        viewWishList1 = new neu.ccs.cs5200.mbps.ldb.view.member.ViewWishList();
        viewDues1 = new neu.ccs.cs5200.mbps.ldb.view.member.ViewDues();
        memberBookSearch1 = new neu.ccs.cs5200.mbps.ldb.view.member.MemberBookSearch();
        manageBooks1 = new neu.ccs.cs5200.mbps.ldb.view.librarian.ManageBooks();
        checkOutBooks1 = new neu.ccs.cs5200.mbps.ldb.view.librarian.CheckOutBooks();
        viewCheckedOutBooks1 = new neu.ccs.cs5200.mbps.ldb.view.member.ViewCheckedOutBooks();
        deleteMembership1 = new neu.ccs.cs5200.mbps.ldb.view.member.DeleteMembership();
        returnBooks1 = new neu.ccs.cs5200.mbps.ldb.view.librarian.ReturnBooks();
        librarianNavigationPanel1 = new neu.ccs.cs5200.mbps.ldb.view.librarian.LibrarianNavigationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MBPS Library Librarian");

        viewPanel.setLayout(new java.awt.CardLayout());
        viewPanel.add(viewProfile1, "memberViewProfile");
        viewPanel.add(viewWishList1, "memberViewWishList");
        viewPanel.add(viewDues1, "memberViewDues");
        viewPanel.add(memberBookSearch1, "memberBookSearch");
        viewPanel.add(manageBooks1, "librarianManageBooks");
        viewPanel.add(checkOutBooks1, "librarianCheckOutBooks");
        viewPanel.add(viewCheckedOutBooks1, "memberViewCheckedOutBooks");
        viewPanel.add(deleteMembership1, "deleteMembership");
        viewPanel.add(returnBooks1, "librarianReturnBooks");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(librarianNavigationPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(viewPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(viewPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
            .add(librarianNavigationPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private neu.ccs.cs5200.mbps.ldb.view.librarian.CheckOutBooks checkOutBooks1;
    private neu.ccs.cs5200.mbps.ldb.view.member.DeleteMembership deleteMembership1;
    private neu.ccs.cs5200.mbps.ldb.view.librarian.LibrarianNavigationPanel librarianNavigationPanel1;
    private neu.ccs.cs5200.mbps.ldb.view.librarian.ManageBooks manageBooks1;
    private neu.ccs.cs5200.mbps.ldb.view.member.MemberBookSearch memberBookSearch1;
    private neu.ccs.cs5200.mbps.ldb.view.librarian.ReturnBooks returnBooks1;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewCheckedOutBooks viewCheckedOutBooks1;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewDues viewDues1;
    private javax.swing.JPanel viewPanel;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewProfile viewProfile1;
    private neu.ccs.cs5200.mbps.ldb.view.member.ViewWishList viewWishList1;
    // End of variables declaration//GEN-END:variables
}
