/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.ccs.cs5200.mbps.ldb.view.librarian;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import neu.ccs.cs5200.mbps.ldb.jdbc.LDBConnector;
import neu.ccs.cs5200.mbps.ldb.model.Book;
import neu.ccs.cs5200.mbps.ldb.model.Genre;
import neu.ccs.cs5200.mbps.ldb.nav.Navigator;
import neu.ccs.cs5200.mbps.ldb.view.util.ViewConstants;

/**
 * Librarian's can add, edit, and delete books to and from the library inventory
 * using this page.
 * 
 * @author Matt
 */
public class ManageBooks extends javax.swing.JPanel {

    /**
     * Creates new form ManageBooks
     */
    public ManageBooks() {
        initComponents();
        registerManageBooksPanel();
    }
    
    /**
     * Register the manage books panel for lazy loading
     */
    private void registerManageBooksPanel() {
        (Navigator.getInstance()).register(ViewConstants.Librarian.MANAGE_BOOKS, this);
    }
    
    /**
     * load the manage books page
     */
    public void loadManageBooks() {
        // set the dropdown box items
        DefaultComboBoxModel cbm1 = (DefaultComboBoxModel) add_genreComboBox.getModel();
        for (int i=0; i<Genre.values().length; i++) {
            cbm1.addElement(Genre.values()[i].getText());
        }
        DefaultComboBoxModel cbm2 = (DefaultComboBoxModel) edit_genreComboBox.getModel();
        for (int i=0; i<Genre.values().length; i++) {
            cbm2.addElement(Genre.values()[i].getText());
        }
        
        registerManageBooks();
    }

    
    private void registerManageBooks() {
        // register the main Manage Books screen with the Navigator
        (Navigator.getInstance()).register(ViewConstants.Librarian.MANAGE_BOOKS, this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageBooksPanel = new javax.swing.JPanel();
        manage_addBookButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        manage_editBookButton = new javax.swing.JButton();
        manage_deleteBookButton = new javax.swing.JButton();
        addBookPanel = new javax.swing.JPanel();
        addBookButton = new javax.swing.JButton();
        add_authorTextField = new javax.swing.JTextField();
        add_isbnTextField = new javax.swing.JTextField();
        add_titleTextField = new javax.swing.JTextField();
        add_publisherTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        add_genreComboBox = new javax.swing.JComboBox();
        add_backButton = new javax.swing.JButton();
        editBookPanel = new javax.swing.JPanel();
        edit_bookSearchPanel = new javax.swing.JPanel();
        bookAttributeComboBox = new javax.swing.JComboBox();
        searchEditBookButton = new javax.swing.JButton();
        bookAttributeTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edit_searchBackButton = new javax.swing.JButton();
        edit_bookEditPanel = new javax.swing.JPanel();
        editBookButton = new javax.swing.JButton();
        edit_authorTextField = new javax.swing.JTextField();
        edit_isbnTextField = new javax.swing.JTextField();
        edit_titleTextField = new javax.swing.JTextField();
        bookIdTextLabel = new javax.swing.JLabel();
        edit_publisherTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        edit_genreComboBox = new javax.swing.JComboBox();
        edit_backButton = new javax.swing.JButton();
        deleteBookPanel = new javax.swing.JPanel();
        delete_bookSearchPanel = new javax.swing.JPanel();
        delete_deleteBookButton = new javax.swing.JButton();
        delete_bookAttributeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        delete_bookAttributeComboBox = new javax.swing.JComboBox();
        delete_searchBackButton = new javax.swing.JButton();
        delete_bookDeletePanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        delete_deleteBooksTable = new javax.swing.JTable();
        deleteBooksButton = new javax.swing.JButton();
        delete_resultsBackButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        manage_addBookButton.setText("Add Book");
        manage_addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_addBookButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Manage Books");

        manage_editBookButton.setText("Edit Book");
        manage_editBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_editBookButtonActionPerformed(evt);
            }
        });

        manage_deleteBookButton.setText("Delete Book");
        manage_deleteBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_deleteBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageBooksPanelLayout = new javax.swing.GroupLayout(manageBooksPanel);
        manageBooksPanel.setLayout(manageBooksPanelLayout);
        manageBooksPanelLayout.setHorizontalGroup(
            manageBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageBooksPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(manageBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(manage_deleteBookButton)
                    .addComponent(manage_editBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manage_addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        manageBooksPanelLayout.setVerticalGroup(
            manageBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageBooksPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(manage_addBookButton)
                .addGap(18, 18, 18)
                .addComponent(manage_editBookButton)
                .addGap(18, 18, 18)
                .addComponent(manage_deleteBookButton)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        add(manageBooksPanel, "librarianManageBooks");

        addBookButton.setText("Add Book");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("ISBN");

        jLabel4.setText("Title");

        jLabel5.setText("Author");

        jLabel6.setText("Publisher");

        jLabel7.setText("Genre");

        jLabel1.setText("Add a New Book");

        add_backButton.setText("Back");
        add_backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addBookPanelLayout = new javax.swing.GroupLayout(addBookPanel);
        addBookPanel.setLayout(addBookPanelLayout);
        addBookPanelLayout.setHorizontalGroup(
            addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addComponent(add_backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addBookButton))
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(add_authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(add_genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        addBookPanelLayout.setVerticalGroup(
            addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(add_genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookButton)
                    .addComponent(add_backButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        add(addBookPanel, "librarianAddBook");

        editBookPanel.setLayout(new java.awt.CardLayout());

        bookAttributeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "ISBN", "Title", "Author", "Publisher", "Genre" }));

        searchEditBookButton.setText("Edit Book");
        searchEditBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditBookButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Search for a Book to Edit");

        edit_searchBackButton.setText("Back");
        edit_searchBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_searchBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edit_bookSearchPanelLayout = new javax.swing.GroupLayout(edit_bookSearchPanel);
        edit_bookSearchPanel.setLayout(edit_bookSearchPanelLayout);
        edit_bookSearchPanelLayout.setHorizontalGroup(
            edit_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_bookSearchPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(edit_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bookAttributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookAttributeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(edit_bookSearchPanelLayout.createSequentialGroup()
                        .addComponent(edit_searchBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchEditBookButton)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        edit_bookSearchPanelLayout.setVerticalGroup(
            edit_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_bookSearchPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(bookAttributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookAttributeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(edit_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_searchBackButton)
                    .addComponent(searchEditBookButton))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        editBookPanel.add(edit_bookSearchPanel, "edit_bookSearch");

        editBookButton.setText("Edit Book");
        editBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookButtonActionPerformed(evt);
            }
        });

        bookIdTextLabel.setText("[id]");

        jLabel10.setText("ISBN");

        jLabel11.setText("ID");

        jLabel12.setText("Title");

        jLabel13.setText("Author");

        jLabel14.setText("Publisher");

        jLabel15.setText("Genre");

        jLabel16.setText("Edit Book Details");

        edit_backButton.setText("Back");
        edit_backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edit_bookEditPanelLayout = new javax.swing.GroupLayout(edit_bookEditPanel);
        edit_bookEditPanel.setLayout(edit_bookEditPanelLayout);
        edit_bookEditPanelLayout.setHorizontalGroup(
            edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_bookEditPanelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_bookEditPanelLayout.createSequentialGroup()
                        .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(edit_authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookIdTextLabel)
                            .addComponent(edit_publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(edit_genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(edit_bookEditPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(edit_backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBookButton)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        edit_bookEditPanelLayout.setVerticalGroup(
            edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_bookEditPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookIdTextLabel)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_isbnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(edit_genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(edit_bookEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBookButton)
                    .addComponent(edit_backButton))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        editBookPanel.add(edit_bookEditPanel, "edit_bookEdit");

        add(editBookPanel, "librarianEditBook");

        deleteBookPanel.setLayout(new java.awt.CardLayout());

        delete_deleteBookButton.setText("Search");
        delete_deleteBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_deleteBookButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Search for Books to Delete");

        delete_bookAttributeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "ISBN", "Title", "Author", "Publisher", "Genre" }));

        delete_searchBackButton.setText("Back");
        delete_searchBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_searchBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delete_bookSearchPanelLayout = new javax.swing.GroupLayout(delete_bookSearchPanel);
        delete_bookSearchPanel.setLayout(delete_bookSearchPanelLayout);
        delete_bookSearchPanelLayout.setHorizontalGroup(
            delete_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_bookSearchPanelLayout.createSequentialGroup()
                .addGroup(delete_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delete_bookSearchPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(delete_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete_bookAttributeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_bookAttributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(delete_bookSearchPanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel9))
                    .addGroup(delete_bookSearchPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(delete_searchBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_deleteBookButton)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        delete_bookSearchPanelLayout.setVerticalGroup(
            delete_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_bookSearchPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(delete_bookAttributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_bookAttributeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(delete_bookSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_searchBackButton)
                    .addComponent(delete_deleteBookButton))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        deleteBookPanel.add(delete_bookSearchPanel, "delete_bookSearch");

        jLabel17.setText("Delete Books");

        delete_deleteBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "ID", "ISBN", "Title", "Author", "Publisher", "Genre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        delete_deleteBooksTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(delete_deleteBooksTable);

        deleteBooksButton.setText("Delete Selected Books");
        deleteBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBooksButtonActionPerformed(evt);
            }
        });

        delete_resultsBackButton.setText("Back");
        delete_resultsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_resultsBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delete_bookDeletePanelLayout = new javax.swing.GroupLayout(delete_bookDeletePanel);
        delete_bookDeletePanel.setLayout(delete_bookDeletePanelLayout);
        delete_bookDeletePanelLayout.setHorizontalGroup(
            delete_bookDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_bookDeletePanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel17)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delete_bookDeletePanelLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(delete_resultsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBooksButton)
                .addGap(62, 62, 62))
        );
        delete_bookDeletePanelLayout.setVerticalGroup(
            delete_bookDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_bookDeletePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(delete_bookDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBooksButton)
                    .addComponent(delete_resultsBackButton))
                .addContainerGap())
        );

        deleteBookPanel.add(delete_bookDeletePanel, "delete_bookDelete");

        add(deleteBookPanel, "librarianDeleteBook");
    }// </editor-fold>//GEN-END:initComponents

    private void manage_addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_addBookButtonActionPerformed
        // navigate to the "Add Book" screen
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.ManageBooks.ADD_BOOK);
    }//GEN-LAST:event_manage_addBookButtonActionPerformed

    private void manage_editBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_editBookButtonActionPerformed
        // navigate to the "Edit Book" screen
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.ManageBooks.EDIT_BOOK);
    }//GEN-LAST:event_manage_editBookButtonActionPerformed

    private void manage_deleteBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_deleteBookButtonActionPerformed
        // navigate to the "Delete Book" screen
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.ManageBooks.DELETE_BOOK);
    }//GEN-LAST:event_manage_deleteBookButtonActionPerformed

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
        // add a book to the database
        
        // get the data from the fields
        String title = this.add_titleTextField.getText();
        String isbn = this.add_isbnTextField.getText();
        String author = this.add_authorTextField.getText();
        String publisher = this.add_publisherTextField.getText();
        int genreIndex = this.add_genreComboBox.getSelectedIndex();
        
        // only advance if all fields are filled out
        if (title.isEmpty() || isbn.isEmpty() || author.isEmpty() || publisher.isEmpty() || genreIndex == -1) {
            JOptionPane.showMessageDialog(this,
                                          "Please fill in all fields",
                                          "Missing Information",
                                          JOptionPane.WARNING_MESSAGE
            );
        }
        
        // fill in the book fields
        Book book = new Book();
        book.setTitle(title);
        book.setIsbn(isbn);
        book.setAuthor(author);
        book.setPublisher(publisher);
        book.setGenre(Genre.values()[genreIndex].getText());
        
        // add the book to the database
        (LDBConnector.getInstance()).addBook(book);
        
        JOptionPane.showMessageDialog(this,
                                      "Book successfully added to the library!",
                                      "Book Added",
                                      JOptionPane.INFORMATION_MESSAGE
        );
        
        // navigate back to the manage books screen
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.MANAGE_BOOKS);
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void editBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookButtonActionPerformed
        // edit the current book's fields
        
        // get the data from the fields
        int bookId = Integer.parseInt(this.bookIdTextLabel.getText());
        String title = this.edit_titleTextField.getText();
        String isbn = this.edit_isbnTextField.getText();
        String author = this.edit_authorTextField.getText();
        String publisher = this.edit_publisherTextField.getText();
        int genreIndex = this.edit_genreComboBox.getSelectedIndex();
        
        // only advance if all fields are filled out
        if (title.isEmpty() || isbn.isEmpty() || author.isEmpty() || publisher.isEmpty() || genreIndex == -1) {
            JOptionPane.showMessageDialog(this,
                                          "Please fill in all fields",
                                          "Missing Information",
                                          JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        // fill in the book details
        Book book = new Book();
        book.setId(bookId);
        book.setIsbn(isbn);
        book.setTitle(title);
        book.setAuthor(author);
        book.setPublisher(publisher);
        book.setGenre(Genre.values()[genreIndex].getText());
        
        // update the book in the database
        (LDBConnector.getInstance()).updateBook(book);
        
        JOptionPane.showMessageDialog(this,
                                      "Book successfully updated!",
                                      "Book Updated",
                                      JOptionPane.INFORMATION_MESSAGE
        );


        // navigate back to the manage books screen
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.MANAGE_BOOKS);
    }//GEN-LAST:event_editBookButtonActionPerformed

    private void delete_deleteBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_deleteBookButtonActionPerformed
        // search for the books that match the user parameters
                // search on the selected field
        String attribute = (String) this.delete_bookAttributeComboBox.getSelectedItem();
        String value = this.delete_bookAttributeTextField.getText();
        
        // load the book results table into memory to manage it
        DefaultTableModel m = (DefaultTableModel) delete_deleteBooksTable.getModel();

        // wipe out the results table
        while (m.getRowCount() > 0) {
            m.removeRow(0);
        }

        // search the database for books matching the select fields
        List<Book> books = (LDBConnector.getInstance()).searchBook(attribute, value);
        
        // add the books to the results table
        for (Book b : books) {
            m.addRow(new Object[] { false,
                                    b.getId(),
                                    b.getIsbn(),
                                    b.getTitle(),
                                    b.getAuthor(),
                                    b.getPublisher(),
                                    b.getGenre()
            });
        }

        // navigate back to the manage books screen
        CardLayout cl = (CardLayout) deleteBookPanel.getLayout();
        cl.show(deleteBookPanel, ViewConstants.Librarian.ManageBooks.DeleteBook.DELETE_BOOK);
    }//GEN-LAST:event_delete_deleteBookButtonActionPerformed

    private void searchEditBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditBookButtonActionPerformed
        // edit the current book's fields
        
        // search on the selected field
        String attribute = (String) this.bookAttributeComboBox.getSelectedItem();
        String value = this.bookAttributeTextField.getText();
        
        List<Book> books = (LDBConnector.getInstance()).searchBook(attribute, value);
        if (books.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                                          "No results for selected attribute",
                                          "No Results",
                                          JOptionPane.WARNING_MESSAGE
            );
        } else {
            Book book = books.get(0);
            
            this.bookIdTextLabel.setText(Integer.toString(book.getId()));
            this.edit_isbnTextField.setText(book.getIsbn());
            this.edit_titleTextField.setText(book.getTitle());
            this.edit_authorTextField.setText(book.getAuthor());
            this.edit_publisherTextField.setText(book.getPublisher());
            this.edit_genreComboBox.setSelectedIndex(Genre.indexOf(book.getGenre()));
            
            // navigate to the edit screen
            CardLayout cl = (CardLayout) editBookPanel.getLayout();
            cl.show(editBookPanel, ViewConstants.Librarian.ManageBooks.EditBook.EDIT_BOOK);
        }
    }//GEN-LAST:event_searchEditBookButtonActionPerformed

    private void deleteBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBooksButtonActionPerformed
        // delete all of the selected items
        DefaultTableModel m = (DefaultTableModel) delete_deleteBooksTable.getModel();
        for (int i=0; i<m.getRowCount(); i++) {
            if ((Boolean) m.getValueAt(i, 0)) {
                // delete the book from the database by id
                int id = (Integer) m.getValueAt(i, 1);
                (LDBConnector.getInstance()).deleteBook(id);
                
                // remove the row from the current table
                m.removeRow(i);
                i--; // adjust row index so it stays accurate
            }
        }

        JOptionPane.showMessageDialog(this,
                                      "Book successfully deleted!",
                                      "Book Deleted",
                                      JOptionPane.INFORMATION_MESSAGE
        );

        // switch the view to the book search results
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.MANAGE_BOOKS);
    }//GEN-LAST:event_deleteBooksButtonActionPerformed

    private void delete_resultsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_resultsBackButtonActionPerformed
        // move back to the delete search screen
        CardLayout cl = (CardLayout) deleteBookPanel.getLayout();
        cl.show(deleteBookPanel, ViewConstants.Librarian.ManageBooks.DeleteBook.SEARCH_BOOK);
    }//GEN-LAST:event_delete_resultsBackButtonActionPerformed

    private void delete_searchBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_searchBackButtonActionPerformed
        // navigate back to the manage book screen
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.MANAGE_BOOKS);
    }//GEN-LAST:event_delete_searchBackButtonActionPerformed

    private void edit_backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_backButtonActionPerformed
        
        this.bookIdTextLabel.setText("[id]");
        this.edit_isbnTextField.setText("");
        this.edit_titleTextField.setText("");
        this.edit_authorTextField.setText("");
        this.edit_publisherTextField.setText("");
        this.edit_genreComboBox.setSelectedIndex(-1);
        
        // navigate back to the edit search panel
        CardLayout cl = (CardLayout) editBookPanel.getLayout();
        cl.show(editBookPanel, ViewConstants.Librarian.ManageBooks.EditBook.SEARCH_BOOK);
    }//GEN-LAST:event_edit_backButtonActionPerformed

    private void add_backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_backButtonActionPerformed
        // navigate back to the manage book screen
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.MANAGE_BOOKS);
    }//GEN-LAST:event_add_backButtonActionPerformed

    private void edit_searchBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_searchBackButtonActionPerformed
        // navigate back to the manage book screen
        CardLayout cl = (CardLayout) getLayout();
        cl.show(this, ViewConstants.Librarian.MANAGE_BOOKS);
    }//GEN-LAST:event_edit_searchBackButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JPanel addBookPanel;
    private javax.swing.JTextField add_authorTextField;
    private javax.swing.JButton add_backButton;
    private javax.swing.JComboBox add_genreComboBox;
    private javax.swing.JTextField add_isbnTextField;
    private javax.swing.JTextField add_publisherTextField;
    private javax.swing.JTextField add_titleTextField;
    private javax.swing.JComboBox bookAttributeComboBox;
    private javax.swing.JTextField bookAttributeTextField;
    private javax.swing.JLabel bookIdTextLabel;
    private javax.swing.JPanel deleteBookPanel;
    private javax.swing.JButton deleteBooksButton;
    private javax.swing.JComboBox delete_bookAttributeComboBox;
    private javax.swing.JTextField delete_bookAttributeTextField;
    private javax.swing.JPanel delete_bookDeletePanel;
    private javax.swing.JPanel delete_bookSearchPanel;
    private javax.swing.JButton delete_deleteBookButton;
    private javax.swing.JTable delete_deleteBooksTable;
    private javax.swing.JButton delete_resultsBackButton;
    private javax.swing.JButton delete_searchBackButton;
    private javax.swing.JButton editBookButton;
    private javax.swing.JPanel editBookPanel;
    private javax.swing.JTextField edit_authorTextField;
    private javax.swing.JButton edit_backButton;
    private javax.swing.JPanel edit_bookEditPanel;
    private javax.swing.JPanel edit_bookSearchPanel;
    private javax.swing.JComboBox edit_genreComboBox;
    private javax.swing.JTextField edit_isbnTextField;
    private javax.swing.JTextField edit_publisherTextField;
    private javax.swing.JButton edit_searchBackButton;
    private javax.swing.JTextField edit_titleTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel manageBooksPanel;
    private javax.swing.JButton manage_addBookButton;
    private javax.swing.JButton manage_deleteBookButton;
    private javax.swing.JButton manage_editBookButton;
    private javax.swing.JButton searchEditBookButton;
    // End of variables declaration//GEN-END:variables
}
